sudo: required
services:
  - docker

before_install:
  - docker build -t dhananjay12/docker-react -f Dockerfile.dev .

script:
  - docker run dhananjay12/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react-workflow"
  env: "DockerReactWorkflow-env"
  bucket_name: "elasticbeanstalk-us-east-2-940712547580"
  bucket_path: "docker-react-workflow"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
